SERVICE_NAME = "TaskFlow API"
HEALTH_PATH = "/health"
DEFAULT_FRONTEND_ORIGIN = "http://localhost:3000"
DEFAULT_DATABASE_URL = "postgresql+psycopg2://taskflow:taskflow@localhost:5432/taskflow"
DEFAULT_AUTH_SECRET_KEY = "change-me-in-production-taskflow-local-secret"
DEFAULT_AUTH_ALGORITHM = "HS256"
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 60
DEFAULT_AUTH_COOKIE_NAME = "taskflow_access_token"
DEFAULT_AUTH_COOKIE_SECURE = False
DEFAULT_AUTH_COOKIE_SAMESITE = "lax"
